---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "autoneg.labels" . | nindent 4 }}
  name: autoneg-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoneg-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "autoneg.serviceAccountName" . | quote }}
  namespace: {{ include "autoneg.namespace" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "autoneg.labels" . | nindent 4 }}
  name: autoneg-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoneg-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "autoneg.serviceAccountName" . | quote }}
  namespace: {{ include "autoneg.namespace" . | quote }}