---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "autoneg.namespace" . | quote }}
