{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "autoneg.fullname" . }}-pdb
  namespace: {{ include "autoneg.namespace" . | quote }}
  labels:
    {{- include "autoneg.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "autoneg.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
