---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{- include "autoneg.labels" . | nindent 4 }}
  name: autoneg-leader-election-role
  namespace: {{ include "autoneg.namespace" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch