---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{- include "autoneg.labels" . | nindent 4 }}
  name: autoneg-leader-election-rolebinding
  namespace: {{ include "autoneg.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoneg-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "autoneg.serviceAccountName" . | quote }}
  namespace: {{ include "autoneg.namespace" . | quote }}
