---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "autoneg.labels" . | nindent 4 }}
  name: {{ default "autoneg-controller-manager-metrics-service" .Values.service.name }}
  namespace: {{ include "autoneg.namespace" . | quote }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
  selector: {{- include "autoneg.selectorLabels" . | nindent 4 }}
