name: |
  Publish Helm chart

on:
  workflow_dispatch: {}
  push:
    branches: 
    - master
    tags:
    - v*
    
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Helm Chart Automation"
          git config user.email "rosmo@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: deploy/chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"